import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { get, post } from "../helpers/helpers";
import { useState } from "react";

export default function Home() {
  const [currentDay, setCurrentDay] = useState(null);
  const [simple, setSimple] = useState(null);
  const [status, setStatus] = useState(null);
  const [statusId, setStatusId] = useState("");
  async function handlePostCurrentDayClick() {
    const resJSON = await post("currentDay");
    setCurrentDay(JSON.stringify(resJSON, null, 2));
  }
  async function handlePostSimpleClick() {
    const resJSON = await post("simple");
    setSimple(JSON.stringify(resJSON, null, 2));
  }
  async function handleGetStatusClick() {
    const resJSON = await get("status", statusId);
    setStatus(resJSON);
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>run</h1>
        <h3>run workflows or query status with id</h3>

        <div className={styles.grid}>
          <div className={styles.card} style={{ overflow: "clip" }}>
            <button onClick={handlePostCurrentDayClick}>
              POST /currentDay !
            </button>
            <div
              className={`${styles.result} ${styles.wideResult} ${styles.veryTallResult}`}
            >
              {currentDay}
            </div>
          </div>
          <div className={styles.card}>
            <button onClick={handlePostSimpleClick}>POST /simple !</button>
            <div
              className={`${styles.result} ${styles.wideResult} ${styles.veryTallResult}`}
            >
              {simple}
            </div>
          </div>
          <div className={styles.card}>
            <button onClick={handleGetStatusClick}>GET /status !</button>
            <div>
              id:{" "}
              <input
                className={styles.input}
                type="text"
                value={statusId}
                onChange={(event) => setStatusId(event.target.value)}
              />
            </div>
            <div
              className={`${styles.result} ${styles.tallerResult} ${styles.wideResult}`}
            >
              {status && `status: ${status.status}`} <br />
              {status && ` workflow: ${status.workflow}`} <br />
              {status && ` id: ${status.id}`}
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
